urls:
  - https://marshal.ohtly.com/index.html
domainWhitelist:
  - marshal.ohtly.com
maxDepth: 10
timeout: !!int 10000 #超时
interval: !!int 500 #请求间隔
maxConcurrency: 10 #同时的请求数
respectRobotsTxt: false
# debug: false
logging:
  level: debug
rules:
  fetch:
    - !!js/regexp ^\/page\/(\d*)\/ # 列表分页
    - !!js/regexp \/([1-3]\d{3}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])).* # 文章
  parse:
    - !!js/regexp \/([1-3]\d{3}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])).* # 文章
  item:
    - name: title # 标题
      expression: //meta[@property="og:title"]/@content
    - name: content # 正文
      expression: //div[@class="article-entry"]
    - name: updateTime # 更新日期
      expression: //meta[@property="og:updated_time"]/@content
# allTimeout: !!int 5000 #总的超时